---
title: "Oregon Early Childhood Map"
output: flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tigris)
library(tidyverse)
library(tmap)
library(janitor)
library(sf)
library(leaflet)
library(mapview)
library(mapdeck)
```

```{r colors}

# Taken from https://oregonearlylearning.com/

oregon_green <- "#007065"
oregon_red <- "#DF3416"
oregon_orange <- "#f78300"

```



```{r get_geodata, include = FALSE}
options(tigris_class = "sf")

oregon_counties <- counties(state = "Oregon",
                            cb = TRUE) %>% 
  clean_names()

oregon_census_tracts <- tracts(state = "Oregon",
                               cb = TRUE) %>% 
  clean_names()


```

```{r include = FALSE}
child_care_facilities <- read_csv("data/child-care-facilities-geocoded.csv") %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = 3857)


```

```{r}
diversity_index <- read_csv("data/diversity-index.csv") %>% 
  clean_names() %>% 
  mutate(diversity = divindx_cy * 500) %>% 
  mutate(geoid = as.character(geoid10)) %>% 
  right_join(oregon_census_tracts) %>% 
  st_as_sf(crs = 3857)

```

```{r}
mapdeck(token = "pk.eyJ1IjoiZGdrZXllcyIsImEiOiJ2WGFJQ2U0In0.ftoZlfudaEIJL7OEf-Mw3Q", 
        style = mapdeck_style("light"), 
        pitch = 15 ) %>%
  add_sf(data = diversity_index,
         tooltip = "divindx_cy",
         auto_highlight = TRUE,
         # highlight_colour = "#00FFFFFF",
         # na_colour = "#eeeeee",
         # elevation = "diversity",
         legend = TRUE,
         fill_opacity = 100,
         fill_colour = "divindx_cy") %>% 
  add_sf(data = child_care_facilities,
         radius = 250,
         tooltip = "facility_name",
         fill_colour = oregon_orange,
         auto_highlight = TRUE,
         focus_layer = TRUE)


```



<!-- ```{r} -->

<!-- pal <- colorNumeric( -->
<!--   palette = "Blues", -->
<!--   domain = diversity_index$divindx_cy) -->

<!-- leaflet() %>% -->
<!--   addProviderTiles(providers$CartoDB.Positron) %>% -->
<!--   # addTiles() %>% -->
<!--   addPolygons(data = diversity_index, -->
<!--               fillOpacity = .75, -->
<!--               fillColor = ~pal(divindx_cy)) -->

<!-- ``` -->



<!-- ```{r} -->
<!-- tmap_mode("view") -->


<!-- tm_basemap(leaflet::providers$CartoDB.Positron) + -->
<!--      tm_shape(oregon_counties) + -->
<!--   tm_fill("statefp", -->
<!--           legend.show = FALSE) + -->
<!--   tm_borders() + -->
<!--   tm_shape(diversity_index) + -->
<!--     tm_fill("divindx_cy", -->
<!--             legend.show = FALSE, -->
<!--             alpha = 0.5) + -->
<!--   tm_borders(alpha = 0.1)  -->


<!-- ``` -->


<!-- ```{r} -->
<!-- mapview(oregon_counties) -->
<!-- ``` -->

